-- Sideout production schema. Apply this in the Supabase SQL editor.
create table if not exists players (id uuid primary key default gen_random_uuid(), name text not null, contact text, positions text[] not null default '{}', elo numeric not null default 1000, created_at timestamptz not null default now());
create table if not exists weeks (id uuid primary key default gen_random_uuid(), session_date date not null, status text not null default 'open' check (status in ('open','closed','completed')), caps jsonb not null default '{"setter":3,"outside":6,"passer":6,"middle":3,"opposite":3}', created_at timestamptz not null default now());
create table if not exists signups (id uuid primary key default gen_random_uuid(), player_id uuid not null references players(id) on delete cascade, week_id uuid not null references weeks(id) on delete cascade, position text not null, status text not null default 'confirmed' check (status in ('confirmed','waitlisted','substitute')), cancel_pin_hash text, created_at timestamptz not null default now(), unique(player_id,week_id));
create table if not exists teams (id uuid primary key default gen_random_uuid(), week_id uuid not null references weeks(id) on delete cascade, team_number int not null, unique(week_id,team_number));
create table if not exists team_assignments (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id) on delete cascade, player_id uuid not null references players(id) on delete cascade, position text not null, unique(team_id,player_id));
create table if not exists matches (id uuid primary key default gen_random_uuid(), week_id uuid not null references weeks(id) on delete cascade, team_a_id uuid not null references teams(id), team_b_id uuid not null references teams(id), team_a_score int, team_b_score int, winner_team_id uuid references teams(id), video_url text, elo_processed boolean not null default false);
create table if not exists elo_history (id uuid primary key default gen_random_uuid(), player_id uuid not null references players(id) on delete cascade, week_id uuid not null references weeks(id) on delete cascade, match_id uuid references matches(id), elo_before numeric not null, elo_after numeric not null, delta numeric not null, created_at timestamptz not null default now());
create index if not exists signups_week_position on signups(week_id,position,status,created_at);
alter table players enable row level security; alter table weeks enable row level security; alter table signups enable row level security; alter table teams enable row level security; alter table team_assignments enable row level security; alter table matches enable row level security; alter table elo_history enable row level security;
create policy "public can view app data" on players for select using (true); create policy "public can view weeks" on weeks for select using (true); create policy "public can view signups" on signups for select using (true); create policy "public can view teams" on teams for select using (true); create policy "public can view assignments" on team_assignments for select using (true); create policy "public can view history" on elo_history for select using (true);
-- Mutating policies should be restricted to Supabase Auth admin users or Edge Functions in production.
